//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace eStationCore.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("eStationCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[People] ([PersonGuid], [Title], [FirstName], [LastName], [HealthState], [Nationality], [IdentityNumber], [BirthDate], [BirthPlace], [PhoneNumber], [EmailAdress], [HomeAdress], [RegistrationDate], [AddUserGuid], [DateAdded], [LastEditDate], [LastEditUserGuid], [IsDeleted], [DeleteUserGuid], [DeleteDate]) VALUES (N&apos;a1bc1aa1-1efc-42ff-bc12-004726372948&apos;, 0, N&apos;Samira&apos;, N&apos;Khalis&apos;, 0, N&apos;Maroc&apos;, N&apos;PO-124547&apos;, N&apos;1995-03-30 00:00:00&apos;, N&apos;Rabat&apos;, N&apos;+212 624-965872&apos;, N&apos;Samira@gmail.com&apos;, NULL, NULL,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbo_People_data {
            get {
                return ResourceManager.GetString("dbo_People_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Staffs] ([StaffGuid], [PersonGuid], [Matricule], [PositionPrincipale], [DepartementPrincipale], [Division], [Qualification], [Diploma], [DiplomaLevel], [Experiences], [FormerJob], [Grade], [HiredDate], [Statut]) VALUES (N&apos;39690a52-3685-4c78-bf7a-0e1588323f71&apos;, N&apos;6d26fe5c-c26f-450e-8481-ec46bb112042&apos;, N&apos;SZ-315-8783&apos;, NULL, N&apos;Pompiste&apos;, NULL, N&apos;Doctorat En Mathematique&apos;, NULL, NULL, 21, NULL, N&apos;Junior&apos;, NULL, 0)
        ///INSERT INTO [dbo].[Staffs] ([StaffGuid], [PersonGuid], [Matricule], [PositionP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbo_Staffs_data {
            get {
                return ResourceManager.GetString("dbo_Staffs_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap defaultStaff {
            get {
                object obj = ResourceManager.GetObject("defaultStaff", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap mainicon {
            get {
                object obj = ResourceManager.GetObject("mainicon", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap No {
            get {
                object obj = ResourceManager.GetObject("No", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait1 {
            get {
                object obj = ResourceManager.GetObject("portrait1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait10 {
            get {
                object obj = ResourceManager.GetObject("portrait10", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait11 {
            get {
                object obj = ResourceManager.GetObject("portrait11", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait12 {
            get {
                object obj = ResourceManager.GetObject("portrait12", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait13 {
            get {
                object obj = ResourceManager.GetObject("portrait13", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait14 {
            get {
                object obj = ResourceManager.GetObject("portrait14", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait15 {
            get {
                object obj = ResourceManager.GetObject("portrait15", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait16 {
            get {
                object obj = ResourceManager.GetObject("portrait16", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait17 {
            get {
                object obj = ResourceManager.GetObject("portrait17", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait18 {
            get {
                object obj = ResourceManager.GetObject("portrait18", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait19 {
            get {
                object obj = ResourceManager.GetObject("portrait19", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait2 {
            get {
                object obj = ResourceManager.GetObject("portrait2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait20 {
            get {
                object obj = ResourceManager.GetObject("portrait20", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait21 {
            get {
                object obj = ResourceManager.GetObject("portrait21", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait22 {
            get {
                object obj = ResourceManager.GetObject("portrait22", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait3 {
            get {
                object obj = ResourceManager.GetObject("portrait3", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait4 {
            get {
                object obj = ResourceManager.GetObject("portrait4", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait5 {
            get {
                object obj = ResourceManager.GetObject("portrait5", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait6 {
            get {
                object obj = ResourceManager.GetObject("portrait6", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait7 {
            get {
                object obj = ResourceManager.GetObject("portrait7", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait8 {
            get {
                object obj = ResourceManager.GetObject("portrait8", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap portrait9 {
            get {
                object obj = ResourceManager.GetObject("portrait9", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed Done.
        /// </summary>
        internal static string Seed_Done {
            get {
                return ResourceManager.GetString("Seed_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap yes {
            get {
                object obj = ResourceManager.GetObject("yes", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
