// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace EStationCore.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m));
        
        string IMigrationMetadata.Id
        {
            get { return "201505121758349_m-"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
